apiVersion: v1
kind: Service
metadata:
  namespace: flexifyio
  name: flexify-service
spec:
  selector:
    app: flexify-ce
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  loadBalancerSourceRanges:
    - <load balancer allowed CIDRs> # Always use these.
    - <load balancer allowed CIDRs> # Always use these.
