apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: flexifyio
  name: flexify-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust size as needed
